package com.imran.ai.interview.dto;

import java.util.List;

/**
 * DTO (Data Transfer Object) definitions for Interview APIs.
 * Placed as static inner classes inside a single wrapper class
 * for convenience in this small project.
 */
public class InterviewDtos {

    /**
     * Request body for generating interview questions.
     */
    public static class QuestionRequest {
        // Full job description text pasted by user
        private String jobDescription;

        // Full resume text pasted by user
        private String resumeText;

        // Number of questions asked from the model (default is 5)
        private int numQuestions = 5;

        public String getJobDescription() {
            return jobDescription;
        }

        public void setJobDescription(String jobDescription) {
            this.jobDescription = jobDescription;
        }

        public String getResumeText() {
            return resumeText;
        }

        public void setResumeText(String resumeText) {
            this.resumeText = resumeText;
        }

        public int getNumQuestions() {
            return numQuestions;
        }

        public void setNumQuestions(int numQuestions) {
            this.numQuestions = numQuestions;
        }
    }

    /**
     * Response body containing list of generated questions.
     */
    public static class QuestionResponse {
        // List of questions generated by the model
        private List<String> questions;

        public QuestionResponse() {
        }

        public QuestionResponse(List<String> questions) {
            this.questions = questions;
        }

        public List<String> getQuestions() {
            return questions;
        }

        public void setQuestions(List<String> questions) {
            this.questions = questions;
        }
    }

    /**
     * Request body for generating answer for one specific question.
     */
    public static class AnswerRequest {
        // Job description text
        private String jobDescription;

        // Candidate resume text
        private String resumeText;

        // Interview question for which we want an answer
        private String question;

        public String getJobDescription() {
            return jobDescription;
        }

        public void setJobDescription(String jobDescription) {
            this.jobDescription = jobDescription;
        }

        public String getResumeText() {
            return resumeText;
        }

        public void setResumeText(String resumeText) {
            this.resumeText = resumeText;
        }

        public String getQuestion() {
            return question;
        }

        public void setQuestion(String question) {
            this.question = question;
        }
    }

    /**
     * Response body containing the generated answer text.
     */
    public static class AnswerResponse {
        // Generated answer text
        private String answer;

        public AnswerResponse() {
        }

        public AnswerResponse(String answer) {
            this.answer = answer;
        }

        public String getAnswer() {
            return answer;
        }

        public void setAnswer(String answer) {
            this.answer = answer;
        }
    }
}
